---
access_key: "{{ lookup('file', '~/aws_access/access_key') }}"
secret_key: "{{ lookup('file', '~/aws_access/secret_key') }}"
ssh_key: "~/.ssh/aws"
private_key: "~/.ssh/aws.pem"
region: sa-east-1
subnet_id: subnet-1ffc6979
image: ami-0b30f38d939dd4b54
type: t3.xlarge
...