---
- name: remove python docker packages
  pip:
    name:
      - docker
      - docker-py
    state: absent

- name: install python docker
  pip:
    name:
      - docker
    state: present

- name: test
  docker_container:
    image: alpine
    name: yolo
...