---
- name: install python package boto and boto3
  pip:
    name:
      - botocore
      - boto
      - boto3
    state: present

- name: Creation de clef
  ec2_key:
    aws_access_key: "{{ aws.access_key }}"
    aws_secret_key: "{{ aws.secret_key }}"
    name: "{{ connection.account_private_key }}"
    region: "{{ aws.region }}"
  register: ec2_key_result

- name: Save private key
  copy: content="{{ ec2_key_result.key.private_key }}" dest="{{ connection.private_key }}" mode=0600
  when: ec2_key_result.changed

- name: Add private key to ssh-agent
  shell: "eval `ssh-agent -s` && ssh-add {{ connection.private_key }}"

- name: install epel-release
  yum:
    name: epel-release
    state: present

- name: install python pip
  yum:
    name: python3-pip
    state: present
    update_cache: yes

- name: update python pip
  shell: "pip3 install --upgrade pip"

#- name: install python docker SDK
#  shell: "pip3 install docker"
...