---
- name: gather security group data
  ec2_instance_info:
    aws_access_key: "{{ lookup('file', '~/aws_access/access_key') }}"
    aws_secret_key: "{{ lookup('file', '~/aws_access/secret_key') }}"
    region: "sa-east-1"
    filters:
      "network-interface.vpc-id": vpc-932139f4
  register: result

- name: Save group info ec2
  copy: content="{{ result[0] }}" dest="~/result" mode=0755
...