---
- name: gather security group data
  ec2_group_info:
    aws_access: ~/aws_access/access_key
    aws_secret: ~/aws_access/secret_key
    filters:
      vpc-id: vpc-932139f4
  register: groups

- name: Save group info ec2
  copy: content="{{ groups }}" dest="~/groups" mode=0755
  when: groups.changed
...