- name: include provisionning variables
  include_vars:
    file: vars/main.yml
    name: i

- name: test looping
  debug:
    msg: "Hostname: {{ item.hostname }}, Group: {{ item.group }}"
  loop: "{{ i.machines }}"
  loop_control:
    index_var: index