---
- name: gather security group data
  ec2_instance_info:
    aws_access_key: "{{ lookup('file', '~/aws_access/access_key') }}"
    aws_secret_key: "{{ lookup('file', '~/aws_access/secret_key') }}"
    region: "sa-east-1"
    filters:
      "network-interface.group-id": sg-02457d8898adbfa34
  register: result

- name: Save group info ec2
  copy: content="{{ result }}" dest="~/result" mode=0755
...