---
- name: gather security group data
  ec2_vpc_net_info:
    aws_access_key: "{{ lookup('file', '~/aws_access/access_key') }}"
    aws_secret_key: "{{ lookup('file', '~/aws_access/secret_key') }}"
    region: "sa-east-1"
  register: groups

- name: Save group info ec2
  copy: content="{{ groups }}" dest="~/groups" mode=0755
...