- name: include provisionning variables
  include_vars:
    file: vars/main.yml
    name: i

- name: test looping
  include: sub.yml
    vars:
      machine: "something"
  #loop: "{{ i.machines }}"
  #loop_control:
  #  index_var: index