---
- name: copy composition files
  copy:
    src: composition
    dest: "/home/sysadmin/composition"

- name: start containers with docker-compose
  shell: "docker-compose -f /home/sysadmin/composition/docker-compose.yml up -d"
...