---
- name: provide new network instances
  import_playbook: provisionning.pb.yml
  when: provide is defined

- hosts: localhost
  tasks:
    - name: run configuration playbook with inventory
      shell: "ansible-playbook configuration.pb.yml -i ~/inventory.ini"
...