#!/bin/bash
# Script to run once on a new centos ansible master

echo "install useful package"
yum install -y epel-release dnf vim bash-completion bash-completion-extras python3 python3-pip

echo "enable auto completion"
source /etc/profile.d/bash_completion.sh

echo "Install ansible"
yum install -y ansible

echo "copy run file"
cp ./run ~/run