#!/bin/bash

# Install useful package
yum install -y epel-release dnf vim bash-completion bash-completion-extras python3 python3-pip

# Enable autocompletion
source /etc/profile.d/bash_completion.sh

# Update pip
pip install --upgrade pip
pip3 install --upgrade pip3

# Install python ansible and docker
python3 -m pip install -y --user ansible docker
