---
- hosts: localhost
  gather_facts: no
  roles:
    - prepare_master
    - role: provide_instances
      when: provides is defined
  post_tasks:
    - meta: refresh_inventory

- hosts: all
  become: yes
  become_method: sudo
  roles:
    - prepare_target
    - install_docker
    - install_gitlab
...