---
- hosts: localhost
  gather_facts: no
  roles:
    - prepare_master
    - role: provide_instances
      when: provides is defined
  post_tasks:
    - meta: refresh_inventory

- hosts: all
  become: yes
  become_method: sudo
  roles:
    - prepare_target
    - install_docker

#- hosts: data
#  become: yes
#  become_method: sudo
#  roles:
#    -

- hosts: application
  become: yes
  become_method: sudo
  roles:
    - setup_application_server

#- hosts: frontend
#  become: yes
#  become_method: sudo
#  roles:
#    -
...