---
- hosts: localhost
  gather_facts: no
  roles:
    - prepare_master
    - role: provide_instances
      when: provides is defined

- hosts: all
  meta: refresh_inventory
  become: yes
  become_method: sudo
  roles:
    - install_docker
...