---
- hosts: localhost
  gather_facts: no
  roles:
    - prepare_master
    - role: provide_instances
      when: provides is defined

- hosts: all
  become: yes
  become_method: sudo
  key_file: ~/.ssh/aws.pem
  roles:
    - install_docker
...

#- name: provide new network instances
#  import_playbook: provisionning.pb.yml
#  when: provides is defined

#- hosts: localhost
#  tasks:
#    - name: run configuration playbook with inventory
#      shell: "ansible-playbook configuration.pb.yml -i ~/inventory.ini"
...