---
# Operations to do one master
- hosts: localhost
  gather_facts: no
  roles:
    - prepare_master
    - role: provide_instances
      when: provides is defined
  post_tasks:
    - meta: refresh_inventory

# Operations to do on all targets
- hosts: all
  become: yes
  become_method: sudo
  roles:
    - prepare_target
    - install_docker

# Specific operations for targets

- hosts: localhost
  gather_facts: no
  become: yes
  become_method: sudo
  roles:
    - install_gitlab
#    - install_openvpn
#
#- hosts: site1
#  become: yes
#  become_method: sudo
#  roles:
#    - install_apache
#
#- hosts: site2
#  become: yes
#  become_method: sudo
#  roles:
#    - install_tomcat
#    - isntall_tomcat_app
#
#- hosts: site3
#  become: yes
#  become_method: sudo
#  roles:
#    - install_python_app
...