- hosts: localhost
  connection: local
  gather_facts: False

  vars:
    access_key: "{{ lookup('file', ~/aws_access/access_key) }}"
    secret_key: "{{ lookup('file', ~/aws_access/secret_key) }}"
    region: eu-central-1
    ssh_key: "~/.ssh/aws"
    vm_name: G4_PEO_
    subnet_id: subnet-3ced7c56
    image: ami-047e03b8591f2d48a
    private_key: "~/.ssh/aws.pem"
    count: 1

  tasks:
    - name: installation de python-pip
      package:
        name:
          - python-pip
        state: present

    - name: installation du module python boto
      pip:
        name:
          - boto
        state: present

    - name: Creation de clef
      ec2_key:
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
        name: "{{ ssh_key }}"
        region: "{{ region }}"
      register: ec2_key_result

    - name: Save private key
      copy: content="{{ ec2_key_result.key.private_key }}" dest="{{ private_key }}" mode=0600
      when: ec2_key_result.changed

    - name: Creation de l'instance
      ec2:
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
        instance_type: t2.micro
        image: "{{ image }}"
        key_name: "{{ ssh_key }}"
        count: "{{ count }}"
        group: default
        region: "{{ region }}"
        wait: yes
        vpc_subnet_id: "{{ subnet_id }}"
        assign_public_ip: yes
        instance_tags:
           Name: "{{ vm_name }}"
      register: ec2

    - name: Save info ec2
      copy: content="{{ ec2 }}" dest="~/details_ec2" mode=0755
      when: ec2.changed
