---
- name: remove old docker packages
  yum:
    name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-engine
    state: absent

- name: install yum-utils
  yum:
    name: yum-utils
    state: latest

- name: add docker repository
  shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

- name: install docker packages
  yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - python-docker
    state: latest
    update_cache: yes

- name: start docker service
  service:
    name: docker
    enabled: yes
    state: restarted

- name: create test container
  docker_container:
    name: alpine_test
    image: alpine:latest
    ports:
      - 4000:4000
    privileged: true

# Test docker installation

- name: check container status
  command: docker ps
  register: result

- debug: var=result.stdout

- name: delete test container
  docker_container:
    name: alpine_test
    state: absent
...