---
- name: create security group
  include: tasks/provide_security_group.yml

- name: remove ancient inventory file
  shell: "> ~/inventory.ini"

- name: init instances list
  set_fact:
    instances: []

- name: instanciate machines of each groups
  include: tasks/provide_group.yml
  vars:
    group: "{{ item }}"
  loop: "{{ machines_groups }}"

- name: Wait for connection
  delegate_to: "{{ item.public_dns_name }}"
  wait_for_connection:
    delay: 60
    timeout: 320
  loop: "{{ instances }}"
...