---
- name: "create inventory group {{ v_group.name }}"
  shell: "echo '[{{ v_group.name }}]' >> {{ v_connection.inventory }}"

- name: "provide machines of group {{ v_group.name }}"
  include: tasks/provide.yml
  vars:
    connection: "{{ v_connection }}"
    machine: "{{ item }}"
    machines: "{{ v_machines }}"
  loop: "{{ v_group.machines }}"

- name: "add empty line in inventory file"
  shell: "echo '' >> {{ v_connection.inventory }}"
...