---
- name: create security group
  ec2_group:
    aws_access_key: "{{ aws.access_key }}"
    aws_secret_key: "{{ aws.secret_key }}"

    region: "{{ aws.region }}"
    vpc_id: "{{ aws.vpc_id }}"

    name: "G4_security_group"
    description: "G4 security group, once to rule them all !"
    rules:
      - cidr_ip: 0.0.0.0/0
        proto: tcp
        ports:
          - 80
        rule_desc: "Allow http traffic"
      - cidr_ip: 0.0.0.0/0
        proto: tcp
        ports:
          - 443
        rule_desc: "Allow https traffic"
  register: ec2

- name: store security group data
  set_fact:
    security_group: "{{ ec2.group_id }}"
...