---
inventory: "~/inventory.ini"

connection:
  account_private_key: "~/.ssh/aws"
  private_key: "~/.ssh/aws.pem"

aws:
  region: sa-east-1
  vpc_id: vpc-932139f4
  subnet_id: subnet-46f2790f
  access_key: "{{ lookup('file', '~/aws_access/access_key') }}"
  secret_key: "{{ lookup('file', '~/aws_access/secret_key') }}"

machines_groups:
  - name: frontend
    machines:
    - name: G4_frontend
      image: ami-0b30f38d939dd4b54
      type: t3.xlarge
      count: 1

  - name: application
    machines:
    - name: G4_applications
      image: ami-0b30f38d939dd4b54
      type: t3.xlarge
      count: 1

  - name: data
    machines:
    - name: G4_data
      image: ami-0b30f38d939dd4b54
      type: t3.xlarge
      count: 1
...