---
inventory: "~/inventory.ini"

connection:
  account_private_key: "~/.ssh/aws"
  private_key: "~/.ssh/aws.pem"

aws:
  region: sa-east-1
  subnet_id: subnet-46f2790f
  access_key: "{{ lookup('file', '~/aws_access/access_key') }}"
  secret_key: "{{ lookup('file', '~/aws_access/secret_key') }}"

security_group:
  id: sg-02457d8898adbfa34

machines_groups:
  - name: frontend
    machines:
      - name: G4_frontend
        image: ami-0b30f38d939dd4b54
        type: t3.xlarge
        count: 1
        volume_size: 20

#  - name: site1
#    machines:
#      - name: G4_site1
#        image: ami-0b30f38d939dd4b54
#        type: t3.xlarge
#        count: 1
#        volume:
#          size: 8
#
#  - name: site2
#    machines:
#    - name: G4_site2
#      image: ami-0b30f38d939dd4b54
#      type: t3.xlarge
#      count: 1
#      volume:
#        size: 8
#
#  - name: site3
#    machines:
#    - name: G4_site3
#      image: ami-0b30f38d939dd4b54
#      type: t3.xlarge
#      count: 1
#      volume:
#        size: 8
#
#  - name: sauvegarde
#    machines:
#    - name: G4_save
#      image: ami-0b30f38d939dd4b54
#      type: t3.xlarge
#      count: 1
#      volume:
#        size: 8
...