---
inventory: "~/inventory.ini"

aws:
  account_private_key: "~/.ssh/aws"
  private_key: "~/.ssh/aws.pem"
  region: sa-east-1
  access_key: "{{ lookup('file', '~/aws_access/access_key') }}"
  secret_key: "{{ lookup('file', '~/aws_access/secret_key') }}"

security_group:
  id: sg-0fdbe517ef51e0957

machines_groups:
  - name: frontend
    machines:
    - name: G4_frontend
      image: ami-0b30f38d939dd4b54
      type: t3.xlarge
      count: 1
      subnet:
        id: subnet-0889844d1ea585fb6
      volume:
        size: 20

  - name: site1
    machines:
    - name: G4_site1
      image: ami-0b30f38d939dd4b54
      type: t3.xlarge
      count: 1
      subnet:
        id: subnet-0534d8d32557e9eaa
      volume:
        size: 8

  - name: site2
    machines:
    - name: G4_site2
      image: ami-0b30f38d939dd4b54
      type: t3.xlarge
      count: 1
      subnet:
        id: subnet-0534d8d32557e9eaa
      volume:
        size: 8

  - name: site3
    machines:
    - name: G4_site3
      image: ami-0b30f38d939dd4b54
      type: t3.xlarge
      count: 1
      subnet:
        id: subnet-0534d8d32557e9eaa
      volume:
        size: 8

  - name: sauvegarde
    machines:
    - name: G4_save
      image: ami-0b30f38d939dd4b54
      type: t3.xlarge
      count: 1
      subnet:
        id: subnet-0534d8d32557e9eaa
      volume:
        size: 20
...