#!/bin/bash
# Script to run once on a new centos7 ansible master

echo "install useful package"
yum install -y epel-release vim bash-completion python3 python3-pip

echo "enable auto completion"
source /etc/profile.d/bash_completion.sh

#echo "Install ansible"
#yum install -y ansible

python3 -m pip install virtualenv
python3 -m virtualenv $PWD/ansible
source $PWD/ansible/bin/activate
python3 -m pip install ansible
chown -R $1:$1 $PWD/ansible
chown -R $1:$1 $PWD/poe-2021-final-project/scripts/run
ln -s $PWD/ansible/bin/activate $PWD/venv

echo "copy run file"
cp $PWD/poe-2021-final-project/scripts/run $PWD/run