#!/bin/bash

source venv
rm -rf $PWD/poe-2021-final-project
git clone https://github.com/Leikt/poe-2021-final-project.git
cd $PWD/poe-2021-final-project
git checkout $1

shift
cd sources
ansible-playbook $@
