---
- name: include provisionning variables
  include_vars:
    file: vars/main.yml
    name: var_infos

- name: include machines to create
  include_vars:
    file: vars/machines.yml
    name: var_machines

- name: prepare the connexion with aws
  include: tasks/preparation.yml
  vars:
    infos: "{{ var_infos }}"
    machines: "{{ var_machines }}"

- name: instanciate machines
  include: tasks/provide.yml
  vars:
    infos: "{{ var_infos }}"
    machine:
      name: G4_TEST
      count: 1
    machines: "{{ var_machines }}"
...