---
- name: include provisionning variables
  include_vars:
    file: vars/main.yml
    name: _infos

- name: include machines to create
  include_vars:
    file: vars/machines.yml
    name: _machines

- name: prepare the connexion with aws
  include: tasks/preparation.yml
  vars:
    infos: "{{ _infos }}"
    machines: "{{ _machines }}"

- name: instanciate machines
  include: tasks/provide.yml
  vars:
    infos: "{{ _infos }}"
    machine: "{{ item }}"
    machines: "{{ _machines }}"
  loop: "{{ _machines.list }}"
...