---
- name: include provisionning variables
  include_vars:
    file: vars/main.yml
    name: prov

- name: prepare the connexion with aws
  include: tasks/preparation.yml
  vars:
    infos: "{{ prov }}"

- name: instanciate machines
  include: tasks/provide.yml
  vars:
    infos: "{{ prov }}"
    machine:
      name: G4_TEST
      group: TEST
      count: 1
...