---
- name: include provisionning variables
  include_vars:
    file: vars/connection.yml
    name: var_connection

- name: include machines to create
  include_vars:
    file: vars/machines.yml
    name: var_machines

- name: prepare the connection with aws
  include: tasks/preparation.yml
  vars:
    connection: "{{ var_connection }}"
    machines: "{{ var_machines }}"

- name: instanciate machines of each groups
  include: tasks/provide_group.yml
  vars:
    v_connection: "{{ var_connection }}"
    v_group: "{{ item }}"
    v_machines: "{{ var_machines }}"
    v_instances: "{{ instances }}"
  loop: "{{ var_machines.groups }}"

...