---
# Require variables
# connexion : access_key, secret_key, ssh_key, region, private_key

- name: install python package boto and boto3
  pip:
    name:
      - botocore
      - boto
      - boto3
    state: latest

- name: Creation de clef
  ec2_key:
    aws_access_key: "{{ connexion.access_key }}"
    aws_secret_key: "{{ connexion.secret_key }}"
    name: "{{ connexion.ssh_key }}"
    region: "{{ machines.region }}"
  register: ec2_key_result

- name: Save private key
  copy: content="{{ ec2_key_result.key.private_key }}" dest="{{ connexion.private_key }}" mode=0600
  when: ec2_key_result.changed

- name: Add private key to ssh-agent
  shell: "eval `ssh-agent -s` && ssh-add {{ connexion.private_key }}"

- name: remove ancient inventory file
  file:
    path: "{{ connexion.inventory }}"
    state: absent

- name: create empty inventory file
  file:
    path: "{{ connexion.inventory }}"
    mode: '0755'
    state: touch
...