---
# Require variables
# connexion : access_key, secret_key, ssh_key
# machines : image, type, region, subnet
# machine : name, count

- name: "Creation de {{ machine.count }} instance(s) : nom={{ machine.name }}"
  ec2:
    aws_access_key: "{{ connexion.access_key }}"
    aws_secret_key: "{{ connexion.secret_key }}"
    key_name: "{{ connexion.ssh_key }}"

    image: "{{ machines.image }}"
    instance_type: "{{ machines.type }}"
    region: "{{ machines.region }}"
    vpc_subnet_id: "{{ machines.subnet_id }}"

    count: "{{ machine.count }}"
    instance_tags:
       Name: "{{ machine.name }}"

    group: default
    assign_public_ip: yes
    wait: yes
  register: ec2

- name: "Add machine {{ machine.name }} to inventory"
  shell: "echo '{{ item.private_ip }}' >> {{ connexion.inventory }}"
  with_items: "{{ ec2.instances }}"
...