---
- name: "Creation de {{ machine.count }} instance(s) : nom={{ machine.name }}"
  ec2:
    aws_access_key: "{{ infos.access_key }}"
    aws_secret_key: "{{ infos.secret_key }}"
    key_name: "{{ infos.ssh_key }}"

    image: "{{ machines.image }}"
    instance_type: "{{ machines.type }}"
    region: "{{ machines.region }}"
    vpc_subnet_id: "{{ machines.subnet_id }}"

    count: "{{ machine.count }}"
    instance_tags:
       Name: "{{ machine.name }}"

    group: default
    assign_public_ip: yes
    wait: yes
  register: ec2

- name: Save info ec2
  copy: content="{{ ec2 }}" dest="~/details_{{ machine.name }}" mode=0755
  when: ec2.changed
...