---
- name: Creation de l'instance
  ec2:
    aws_access_key: "{{ infos.access_key }}"
    aws_secret_key: "{{ infos.secret_key }}"
    instance_type: "{{ infos.type }}"
    image: "{{ infos.image }}"
    key_name: "{{ infos.ssh_key }}"
    count: "{{ machine.count }}"
    group: default
    region: "{{ infos.region }}"
    wait: yes
    vpc_subnet_id: "{{ infos.subnet_id }}"
    assign_public_ip: yes
    instance_tags:
       Name: "{{ machine.name }}"
  register: ec2

- name: Save info ec2
  copy: content="{{ ec2 }}" dest="~/details_{{ machine.name }}" mode=0755
  when: ec2.changed
...