---
# Require variables
# connexion : access_key, secret_key, ssh_key
# machines : image, type, region, subnet
# machine : name, count

- name: "Creation de {{ machine.count }} instance(s) : nom={{ machine.name }}"
  ec2:
    aws_access_key: "{{ connection.access_key }}"
    aws_secret_key: "{{ connection.secret_key }}"
    key_name: "{{ connection.ssh_key }}"

    image: "{{ machines.image }}"
    instance_type: "{{ machines.type }}"
    region: "{{ machines.region }}"
    vpc_subnet_id: "{{ machines.subnet_id }}"

    count: "{{ machine.count }}"
    instance_tags:
       Name: "{{ machine.name }}"

    group: default
    assign_public_ip: yes
    wait: yes
  register: ec2

- name: "Add machine {{ machine.name }} to inventory"
  shell: "echo '{{ item.public_ip }}' >> {{ connection.inventory }}"
  with_items: "{{ ec2.instances }}"

- name: "Append instance to created instances"
  set_fact:
    instances: "{{ instances + [ item ] }}"
  with_items: "{{ ec2.instances }}"

#- name: "Wait for connection"
#  delegate_to: "{{ item.public_dns_name }}"
#  wait_for_connection:
#    delay: 60
#    timeout: 320
#  loop: "{{ ec2.instances }}"
...