concurrent = 4
log_level = "warning"

[[runners]]
    name="ruby:2.6.runner"
    url="http://15.228.93.207/"
    token="4k2zjCr_UizC5KyNjpQT"
    executor="docker"

    [runners.docker]
        host=""
        image="ruby:2.6"
        privileged= false