---
- name: install useful packages
  yum:
    name:
      - epel-release
      - vim
      - dnf
      - bash-completion
      - python-pip
    state: present

- name: enable auto-completion
  shell: source /etc/profile.d/bash_completion.sh
...