---
- name: install epel-release
  yum:
    name: epel-release
    state: present

- name: install python pip
  yum:
    name: python3-pip
    state: present
    update_cache: yes

- name: update python pip
  shell: "pip3 install --upgrade pip"
...