---
- name: install epel-release
  yum:
    name: epel-release
    state: present

- name: install python pip
  yum:
    name: python2-pip
    state: present
    update_cache: yes

- name: update pip
  shell: "pip install --upgrade pip"
...